// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvQF7R7DlXqUzSa3SWoBAiG3-N2N5jbq0',
    appId: '1:601806799262:web:682f570a5afa229972968f',
    messagingSenderId: '601806799262',
    projectId: 'versekeeper-julia',
    authDomain: 'versekeeper-julia.firebaseapp.com',
    storageBucket: 'versekeeper-julia.firebasestorage.app',
    measurementId: 'G-5VN6653CNR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO_NVwkvJDrefsSPhDabHILeunX1OkwEM',
    appId: '1:601806799262:android:c2cd7b88fa8c1f1672968f',
    messagingSenderId: '601806799262',
    projectId: 'versekeeper-julia',
    storageBucket: 'versekeeper-julia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACEtm0BN5f3TpsySz1rEt-gXO5zrbxT1k',
    appId: '1:601806799262:ios:778c28e029db02a872968f',
    messagingSenderId: '601806799262',
    projectId: 'versekeeper-julia',
    storageBucket: 'versekeeper-julia.firebasestorage.app',
    iosBundleId: 'com.example.versekeeper',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACEtm0BN5f3TpsySz1rEt-gXO5zrbxT1k',
    appId: '1:601806799262:ios:778c28e029db02a872968f',
    messagingSenderId: '601806799262',
    projectId: 'versekeeper-julia',
    storageBucket: 'versekeeper-julia.firebasestorage.app',
    iosBundleId: 'com.example.versekeeper',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvQF7R7DlXqUzSa3SWoBAiG3-N2N5jbq0',
    appId: '1:601806799262:web:e0a5e296569e4d5872968f',
    messagingSenderId: '601806799262',
    projectId: 'versekeeper-julia',
    authDomain: 'versekeeper-julia.firebaseapp.com',
    storageBucket: 'versekeeper-julia.firebasestorage.app',
    measurementId: 'G-7NJ60SJWLV',
  );
}
